# code: language=ansible

nmcli:
  # list of community.general.nmcli
  args:
    - state: present
      type: ethernet
      conn_name: ens192
      ifname: ens192
      ip4: 192.168.1.203/24
      gw4: 192.168.1.1

  # list of ansible.builtin.command
  commands:
    # bug fix for static ip
    - nmcli connection modify ens192 ipv4.method manual
    # disable default route
    - nmcli connection modify ens192 ipv4.never-default yes
    - nmcli connection modify ens192 connection.zone 'trusted'
    - nmcli connection up
